In [2]:
import numpy as np

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [3]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [4]:
A.dot(B)

array([[  4, -11],
       [ 12,  -3]])

In [5]:
B.dot(A)

array([[ 1, -8],
       [15,  0]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [6]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [7]:
3 * A - 2 * B + 4 * C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [8]:
A = np.array([[4, 1], [5, -2], [2, 3]])

In [9]:
A.dot(A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [10]:
A.T.dot(A)

array([[45,  0],
       [ 0, 14]])


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [37]:
class MyMatrix:
    def __init__(self, data):
        self.__data = data
        self.__check_input_type__()
        self.__m = self.__calc_dimensions__()[0]
        self.__n = self.__calc_dimensions__()[1]
        self.__chek_consistency__()
        self.__check_numbers__()

    def __calc_dimensions__(self):
        m = len(self.__data)
        n = len(self.__data[0])
        return m, n

    def __check_numbers__(self):
        for i in range(self.__m):
            for j in range(self.__n):
                if not isinstance(self.__data[i][j], (int, float)):
                    raise ValueError(f"Element in index[{i}][{j}] is not number")

    def __chek_consistency__(self):
        for i in range(self.__m):
            if len(self.__data[i]) != self.__n:
                raise IndexError(f"Wrong length of line {i} in matrix")

    def __check_input_type__(self):
        if not isinstance(self.__data, (list, tuple)):
            raise TypeError("Wrong input data, must be list of list or tuple of tuple or shuffled")
        for line in self.__data:
            if not isinstance(line, (list, tuple)):
                raise TypeError("Wrong input data, must be list of list or tuple of tuple or shuffled")

    def __str__(self):
        return self.data
    
    def __repr__(self):
        return self.data

    @property
    def data(self):
        out = str()
        for i in range(self.__m):
            out += str(self.__data[i])
            out += "\n"
        return out

    @property
    def shape(self):
        return self.__m, self.__n

    def dot(self, matrix):
        if not isinstance(matrix, MyMatrix):
            raise TypeError("Other matrix must be instance of MyMatrix class")
        if self.__n != matrix.shape[0]:
            raise IndexError("Can't multiply such matrixes")
        out = [[0 for n in range(matrix.__n)] for m in range(self.__m)]
        for i in range(self.__m):
            for j in range(matrix.__n):
                line_el = self.__data[i]
                columns_el = [matrix.__data[el][j] for el in range(matrix.__m)]
                out[i][j] = self.__redusing__(line_el, columns_el)
        return MyMatrix(out)

    def __redusing__(self, line, column):
        out = 0
        for i in range(len(line)):
            out += line[i] * column[i]
        return out


In [18]:
A = MyMatrix([[1, 2], [3, 4]])
B = MyMatrix([[1, 2, 3], [3, 4, 5], [3, 4, 5]])


In [19]:
print(A.dot(B))

IndexError: Can't multiply such matrixes

In [20]:
C = MyMatrix([[1, 2, 3], [1, 2]])

IndexError: Wrong length of line 1 in matrix

In [38]:
D = MyMatrix([[1, -3, 5, -4, 6], [10, -3, 6, 9, -12], [1, 0, -5, 7, -3]])
F = MyMatrix([[5, 3, -1], [0, 12, -10], [1, 2, 1], [-3, 12, -10], [0, -7, 2]])

In [41]:
G = D.dot(F)
G

[22, -113, 86]
[29, 198, -88]
[-21, 98, -82]

In [15]:
D_np = np.array([[1, -3, 5, -4, 6], [10, -3, 6, 9, -12], [1, 0, -5, 7, -3]])
F_np = np.array([[5, 3, -1], [0, 12, -10], [1, 2, 1], [-3, 12, -10], [0, -7, 2]])

In [16]:
D_np.dot(F_np)

array([[  22, -113,   86],
       [  29,  198,  -88],
       [ -21,   98,  -82]])